# Задание 1
### Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [114]:
import numpy as np

arr = np.arange(1, 10).reshape(3,3)
arr *= 2
arr[arr > 10] = 0
print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


# Задание 2
### Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [115]:
arr = np.random.randint(1, 101, size=20)
print(f"Исходный массив: {arr}")
divide_by_5 = arr[arr % 5 == 0]
print(f"Элементы массива, которые делятся на 5 без остатка: {divide_by_5}")
arr[arr % 5 == 0] = -1
print(f"Обновленный массив: {arr}")

Исходный массив: [ 41 100  97   8  88  20  47  18  12  76  96  37  69  32  95  28   6  20
  21  78]
Элементы массива, которые делятся на 5 без остатка: [100  20  95  20]
Обновленный массив: [41 -1 97  8 88 -1 47 18 12 76 96 37 69 32 -1 28  6 -1 21 78]


# Задание 3
### Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. Объедините эти массивы в один двумерный массив (по строкам). Разделите полученный массив на два массива, каждый из которых содержит 5 элементов. Выведите все промежуточные и итоговые результаты.

In [116]:
arr1 = np.random.randint(0, 51, size=(1, 5))
arr2 = np.random.randint(0, 51, size=(1, 5))

print("Первый массив:", arr1)
print("Второй массив:", arr2)

combined = np.vstack((arr1, arr2))
print("Объединённый двумерный массив:\n", combined)

split1, split2 = np.vsplit(combined, 2)
print("Первый разделённый массив:", split1)
print("Второй разделённый массив:", split2)

Первый массив: [[ 5 46 13 28 16]]
Второй массив: [[30 22 46 50 22]]
Объединённый двумерный массив:
 [[ 5 46 13 28 16]
 [30 22 46 50 22]]
Первый разделённый массив: [[ 5 46 13 28 16]]
Второй разделённый массив: [[30 22 46 50 22]]


# Задание 4
### Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [117]:
arr = np.linspace(-10, 10, 50)
print(arr)

arr_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print("\nСумма всех элементов:", arr_sum)
print("Сумма положительных элементов:", positive_sum)
print("Сумма отрицательных элементов:", negative_sum)

[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


# Задание 5
### Создайте: Единичную матрицу размером 4×4. Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы). Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [118]:
ed = np.eye(4)
diag = np.diag([5, 10, 15, 20])

sum_ed = np.sum(ed)
sum_diag = np.sum(diag)

print("Сумма элементов единичной матрицы:", sum_ed)
print("Сумма элементов диагональной матрицы:", sum_diag)

if sum_ed > sum_diag:
    print("Сумма элементов единичной матрицы больше")
elif sum_ed < sum_diag:
    print("Сумма элементов диагональной матрицы больше")
else:
    print("Суммы равны")

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше


# Задание 6
### Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите: Их сумму, их разность, их поэлементное произведение.

In [119]:
A1 = np.random.randint(1, 21, size=(3, 3))
A2 = np.random.randint(1, 21, size=(3, 3))

print("Матрица 1:\n", A1)
print("Матрица 2:\n", A2)

print("Сумма:\n", A1 + A2)
print("Разность:\n", A1 - A2)
print("Поэлементное произведение:\n", A1 * A2)

Матрица 1:
 [[12  3  2]
 [ 1  5  8]
 [ 7 16 19]]
Матрица 2:
 [[12  9 19]
 [ 1  9  6]
 [18 12 16]]
Сумма:
 [[24 12 21]
 [ 2 14 14]
 [25 28 35]]
Разность:
 [[  0  -6 -17]
 [  0  -4   2]
 [-11   4   3]]
Поэлементное произведение:
 [[144  27  38]
 [  1  45  48]
 [126 192 304]]


# Задание 7
### Создайте две матрицы NumPy: Первую размером 2×3, заполненную случайными числами от 1 до 10. Вторую размером 3×2, заполненную случайными числами от 1 до 10. Выполните матричное умножение (@ или nр. dot ) и выведите результат.

A = np.random.randint(1, 11, size=(2, 3))
B = np.random.randint(1, 11, size=(3, 2))
print("Первая матрица:\n", A)
print("Вторая матрица:\n", B)

result = np.dot(A, B)

print("Результат матричного умножения\n", result)

# Задание 8
### Создайте случайную квадратную матрицу 3×3. Найдите и выведите: Определитель этой матрицы, Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена). Используйте функции np.linalg.det и nр.linalg.inv.

In [121]:
A = np.random.rand(3, 3)
print("Случайная матрица:\n", A)

A_det = round(np.linalg.det(A), 3)
print("\nОпределитель матрицы", A_det)

if A_det == 0:
    print("\nМатрица вырождена!")
else:
    A_inv = np.linalg.inv(A)
    print("\nОбратная матрица:\n", A_inv)

Случайная матрица:
 [[0.76521644 0.5044308  0.39237983]
 [0.44653482 0.8948512  0.20046605]
 [0.28390743 0.65306577 0.87730492]]

Определитель матрицы 0.346

Обратная матрица:
 [[ 1.88841224 -0.53779314 -0.72171668]
 [-0.9666182   1.61643726  0.06296635]
 [ 0.10843549 -1.02923893  1.32653942]]


# Задание 9
### Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите: Исходную матрицу, Транспонированную матрицу, След матрицы (сумму элементов на главной диагонали). Используйте np.trace для нахождения следа.

In [122]:
A = np.random.randint(1, 51, size = (4, 4))
A_t = np.transpose(A)
A_trace = np.trace(A)

print("Исходная матрица:\n", A)
print("Транспонированная матрица:\n", A_t)
print("След матрицы:\n", A_trace)

Исходная матрица:
 [[28 38 21 29]
 [ 6  9 39 46]
 [39  2 11 45]
 [22 37 40 15]]
Транспонированная матрица:
 [[28  6 39 22]
 [38  9  2 37]
 [21 39 11 40]
 [29 46 45 15]]
След матрицы:
 63


# Задание 10
### Решите систему линейных уравнений вида:
#### 2x + 3y - z = 5
#### 4x - y + 2z = 6
#### -3x + 5y + 4z = -2

In [123]:
A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

x = np.linalg.solve(A, B)
print("Решение системы (x, y, z):", x)

Решение системы (x, y, z): [1.63963964 0.57657658 0.00900901]


# Индивидуальное задание
### Задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.
### Условие: Распределение инвестиций. Компания выделила 1 000 000 рублей на три проекта. Первый проект получает в два раза больше, чем второй, а третий получает на 200 000 рублей больше, чем второй. Сколько денег получит каждый проект?
### Пусть: x1 - деньги для 1 проекта, x2 - деньги для 2 проекта, x3 - деньги для 3 проекта
### Общая сумма: x1 + x2 + x3 = 1000000, x1 = 2x2, x1 - 2x2 = 0, x3 = x2 + 200000, -x2 + x3 = 200000
### Тогда получаем систему уравнений:
### x1 + x2 + x3 = 1000000
### x1 - 2x2 = 0
### -x2 + x3 = 200000

In [125]:
import numpy as np

# Матрица коэффициентов
A = np.array([
    [1, 1, 1],
    [1, -2, 0],
    [0, -1, 1]
], dtype=float)

# Вектор правой части
B = np.array([1000000, 0, 200000], dtype=float)

print("=== Метод Крамера ===")
# Вычисляем определитель A
det_A = np.linalg.det(A)

# Создаём копии A и заменяем столбцы
def cramer(A, B, i):
    A_i = A.copy()
    A_i[:, i] = B
    return np.linalg.det(A_i) / det_A

x1 = cramer(A, B, 0)
x2 = cramer(A, B, 1)
x3 = cramer(A, B, 2)

print(f"x1 = {x1:,.0f} руб")
print(f"x2 = {x2:,.0f} руб")
print(f"x3 = {x3:,.0f} руб")


print("\n=== Матричный метод (через обратную матрицу) ===")
A_inv = np.linalg.inv(A)
X_mat = A_inv @ B
print(f"x1 = {X_mat[0]:,.0f} руб")
print(f"x2 = {X_mat[1]:,.0f} руб")
print(f"x3 = {X_mat[2]:,.0f} руб")

print("\n=== Метод np.linalg.solve ===")
X_solve = np.linalg.solve(A, B)
print(f"x1 = {X_solve[0]:,.0f} руб")
print(f"x2 = {X_solve[1]:,.0f} руб")
print(f"x3 = {X_solve[2]:,.0f} руб")

print("\n=== Проверка ===")
print("Все методы дают одинаковый результат:", np.allclose(X_mat, X_solve))

=== Метод Крамера ===
x1 = 400,000 руб
x2 = 200,000 руб
x3 = 400,000 руб

=== Матричный метод (через обратную матрицу) ===
x1 = 400,000 руб
x2 = 200,000 руб
x3 = 400,000 руб

=== Метод np.linalg.solve ===
x1 = 400,000 руб
x2 = 200,000 руб
x3 = 400,000 руб

=== Проверка ===
Все методы дают одинаковый результат: True
