In [106]:
import numpy as np
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [107]:
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1 -3]
 [ 2  5]]
[[ 1. -3.]
 [ 2.  5.]]


In [108]:
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [109]:
B = np.matrix('7 6; 1 8')
L2 = np.linalg.inv(A.dot(B))
R2 = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L2)
print(R2)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
