In [50]:
import numpy as np
print(np.random.permutation(7))
a = ['a', 'b', 'c', 'd', 'e']
print(np.random.permutation(a))

[4 2 3 0 6 5 1]
['b' 'a' 'e' 'd' 'c']


In [51]:
arr = np.linspace(0, 10, 5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [52]:
arr_mix = np.random.permutation(arr)
print(arr_mix)

[ 0.   7.5 10.   2.5  5. ]


In [53]:
index_mix = np.random.permutation(len(arr_mix))
print(index_mix)
print(arr[index_mix])

[4 2 3 0 1]
[10.   5.   7.5  0.   2.5]
