In [54]:
import numpy as np
v_hor_np = np.array([1, 2])
print(v_hor_np)

[1 2]


In [55]:
v_hor_zeros_v1 = np.zeros((5, ))
print(v_hor_zeros_v1)

[0. 0. 0. 0. 0.]


In [56]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2)

[[0. 0. 0. 0. 0.]]


In [57]:
v_hor_one_v1 = np.ones((5, ))
print(v_hor_one_v1)
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]]


In [58]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [59]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [60]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
